---
title: "Company X delivery"
root: "lectures"
output: "output/company-x"
course_slides: "company-x-course.pdf"
course_archive: "company-x-course.zip"
chapters:
  "Hello world":
    root: "hello-world"
    assets: "resources"
    lectures:
      "Hello world": "hello-world.md"
      "Setting up the environment": "environment.md"
      "Variables": "variables.md"
      "Functions": "functions.md"
    extras:
      - "exercises/hello-world"
      - "exercises/functions"
      - "how-to-setup-vscode.pdf"
  "Data types":
    root: "data-types"
    lectures:
      "Data types": "data-types.md"
      "Strings": "strings.md"
      "Numbers": "numbers.md"
      "Booleans": "booleans.md"
      "Arrays": "arrays.md"
      "Objects": "objects/objects.md"
    extras:
      - "exercises/objects"
