name: Test eely

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Lint with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
      - name: Test with pytest
        run: |
          cd test
          pytest -rP

  smoke-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g @marp-team/marp-cli@v2.4.0
      - name: Fetch sample repository
        uses: actions/checkout@v3
        with:
          repository: platisd/eely-sample-repository
          path: smoketest
      - name: Smoketest HTML generation
        run: |
          python3 eely.py --html smoketest/beginning-course.yaml
      - name: Smoketest PDF generation
        run: |
          python3 eely.py --pdf smoketest/beginning-course.yaml
